name: bi_test
dependencies:
    - python==3.12
    - pip
    - pip:
      - numpy
      - pandas
      - scipy
      - scikit-learn
      - matplotlib
      - seaborn
      - jupyterlab
      - torch
      - tables
      - ipywidgets
